# image:  marcoturi/ionic:latest

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    # - npm install
    # - npm run build
    # - rm -rf public
    - mv build web
  artifacts:
    paths:
      - web
  only:
    - master
