export default [
    "When is the last time you sincerely apologized?",
    "If you get hold of a time machine, ‘when’ would you like to go?",
    "What’s the weirdest thing about you? Are you proud of it?",
    "Do you sleep naked?",
    "Have you been in any fights while in school?",
    "Have your ever sleep-walked?",
    "Can you touch your tongue to your nose?",
    "If you had to choose brains or beauty, which would you pick?",
    "What is your most embarrassing vomit story?",
    "Who is your favorite Disney character?",
    "What was your favorite cartoon when you were little?",
    "Have you ever broken something and blamed someone else?",
    "What is the favorite thing you’ve dreamt about?",
    "Would you prefer to be smart or happy, and why?",
    "Have you ever been hypnotized?",
    "What was the best day of your life?",
    "If you had a time machine, to which time period would you go?",
    "What’s the worst gift you’ve ever received?",
    "Would you ever get on a dating website?",
    "Do you keep a diary or a journal?",
    "What was the nastiest prank you ever played on someone?",
    "What would you do if you were invisible for a day?",
    "Who did you vote for? Or who would you vote for?",
    "If there was no such thing as money, what would you do with your life?",
    "If your life were made into a movie who would play you?",
    "Was there any teacher you thought was hot? Which one? Why?",
    "If you could live anywhere in the world, where would you live?",
    "How many times have you snuck out of the house?",
    "Have you ever snuck anyone into the house?",
    "Have you ever thrown up in someone’s car?",
    "Are you in any sports?",
    "What food would you eat everyday if you could?",
    "What’s your biggest pet peeve?",
    "What’s the worst gift you’ve ever given someone?",
    "Have you ever used a water pipe? If so, tell about your experience!",
    "If you could be any animal, which one would you be?",
    "Would you rather live in a house in a suburb or in an apartment in a big city?",
    "If you could try out any job for a day, what would it be?",
    "If you could be any dinosaur, which would it be?",
    "What are your worst habits?",
    "If you could date anyone in the world, who would it be?",
    "What type of delicious treat turns you on?",
    "If you had only 1 more day to live, what would you do?",
    "Who is your ugliest friend?",
    "Would you rather live in a world of magic or superheroes?",
    "Which fictional charcater would you love to marry?",
    "Do you prefer to be by yourself or with someone else?",
    "Have you ever sneaked snacks when your parents weren’t looking?",
    "What college do you plan on going to?",
    "What is your favorite song?",
    "Have you ever lied in Truth or Dare questions?",
    "Do you ever fantasize about starting a band/opening a restaurant? What would you call it?",
    "If you had to be renamed a name other than your own, which would you pick?",
    "What is the funniest thing your grandparents have ever said?",
    "How many best friends have you had during your lifetime?",
    "Have you ever walked in on your parents?",
    "What do you like most about your girlfriend/boyfriend?",
    "If you could get rid of one household chore, what would it be?",
    "Describe yourself at age 30.",
    "What’s the most beautiful place you’ve ever been to?",
    "If Jurassic Park were real, would you visit it?",
    "If you could invent anything, what would it be?",
    "If you had to listen to one genre of music for the rest of your life, what would it be?",
    "Name a time when you used somebody for your personal gain.",
    "If you won the lottery and had to give it away to someone from this group, who would it be and why?",
    "What’s the longest you’ve ever gone without taking a bath?",
    "What do you think is your biggest physical flaw?",
    "How flexible are you?",
    "Does your best friend call you their best friend?",
    "What is the best vacation you’ve ever been on?",
    "What is something you’ve always wanted to try but have been too scared of?",
    "Name something you’ve always wanted, but is too expensive to buy.",
    "If you could take away one bad thing in the world, what would it be?",
    "Who is your best-looking teacher that you have ever had?",
    "If you could be a boy or girl for one day… Would you and why?",
    "What is the most annoying thing that one of your siblings has done?",
    "What TV show are you embarrassed about watching?",
    "What is your favorite school subject?",
    "If someone made a movie about your life, what would they call it? Who gets your role?",
    "What foreign languages would you like to learn?",
    "Have you ever had a crush on someone that your best friend has dated?",
    "Would you ever date someone you met online?",
    "Have you ever had a crush on your best friend?",
    "Are there any rules or social norms that piss you off?",
    "Could you go one month without talking to your friends?",
    "Have you ever been caught doing something dirty? If so, what did you do?",
    "Do you have a job? If so, what is your favorite thing about it?",
    "What is your best talent?",
    "Would you drop out of school if you were to win the lottery?",
    "If you had to change one physical thing about yourself, what would it be?",
    "Do you ever fantasize about starting a band/opening a restaurant? What would it be called?",
    "If you had to murder someone, who would it be?",
    "What is the name of your first crush?",
    "Do you bite your nails?",
    "Who’s your celebrity crush?",
    "Would you rather be a horse or a cow?",
    "If you could own your own business one day, what would it be?",
    "Who was your first crush or who is your current crush?",
    "What music are you embarrassed about listening to?",
    "Have you ever pulled a prank on your teacher? Tell your story!",
    "What are you thinking about at the moment?",
    "Tell us a drunken story of yours.",
    "Have you ever taken money from your roommate?",
    "What’s the most embarrassing situation you’ve ever farted in?",
    "Can you see yourself being married to the creepiest kid at your school someday?",
    "What is the most exciting dream you have ever had?",
    "Predict the future for the friend on your left.",
    "Do you know the lyrics for the entire national anthem?",
    "Have you ever streaked?",
    "If you knew the world was about to end, what would you do?",
    "What is the longest time you have ever been grounded?",
    "Have you ever worn the same clothes for more than three days?",
    "What is your favorite board game to play with your family?",
    "What is the worst food you have ever eaten?",
    "Which one of your parents are you closer to?",
    "Write your name upside down.",
    "Do the macarena silently until it is your turn again.",
    "Get wrapped from head to toe in toilet paper.",
    "Have a full conversation with a broom.",
    "Draw a stick figure with the pen held in your mouth.",
    "Go outside and yell ‘Happy New Year!‘.",
    "Talk while holding your tongue.",
    "Ask the person on your left to make up a dare for you.",
    "Act like a race car.",
    "Be blindfolded for the next 3 rounds.",
    "Go outside and yell “I believe in fairies” loudly three times while clapping your hands as fast as you can.",
    "Jump while holding a cup full of water above your head without spilling it.",
    "Stick round labels all over yourself and pretend to have chicken pox.",
    "Act like a gorilla for one minute.",
    "Recite the multiplication table of 2.",
    "Wrap your head in your t-shirt and sit like that for one round.",
    "Don’t say ‘yes’ or ‘no’ for 1 minute.",
    "Stand like a flamingo for the next four rounds.",
    "Post an embarrassing picture of yourself online.",
    "Using only your elbows, write a Facebook status and post it.",
    "Do an impression of your favorite celebrity.",
    "Make up a story about the item to your right.",
    "Mime your dream job.",
    "Do 50 jumping jacks.",
    "Make a headdress out of toilet paper and pose for photos.",
    "Get blindfolded and spin around 10 times and walk down the street and back.",
    "Write a Facebook (or other social media) post only using your toes.",
    "Slap the person to your left on the booty.",
    "Snort a line of sugar.",
    "Eat a spoon of salt.",
    "Imitate a Chinese accent for 2 turns.",
    "Try to sell ice in the street.",
    "Send an email to one of your teachers, telling them about how your day is going.",
    "Give someone in the group a piggyback ride around the room.",
    "Paint your fingernails with a crayon.",
    "Read the last message you received out loud.",
    "Get some powder in your hands and smack the person to your left on the cheek.",
    "Massage your neighbour’s shoulders.",
    "Imagine you are a pair of chicken nuggets in a frying pan.",
    "Imitate a celebrity and imagine yourself on a red carpet in front of the players.",
    "You have to do the next dare someone else gets together with them.",
    "Drink a salty glass of milk.",
    "Say the words “in bed” after everything you say for the next 10 minutes.",
    "Smell a player’s armpit.",
    "Say ‘banana’ after everything you say until it is your turn again.",
    "Insult each player. Drink for each player you cannot insult.",
    "Close your eyes while the group puts something edible and non-toxic in your mouth. You must eat it.",
    "Pretend that you are in an invisible wheelchair.",
    "Prank call someone you know! Perhaps someone that couldn’t make it that night.",
    "You can’t say ‘yes’ or ‘no’ for 3 turns.",
    "Draw something on the person on your right.",
    "Act like a clown while counting up to 20.",
    "Call your crush and just breathe into the phone.",
    "Open the window and try to get someone on the street to wave to you.",
    "Lick the food of your choice on the back of someone’s neck.",
    "Sellotape a teaspoon to your forehead.",
    "Go to the kitchen and eat something that is not meant to be eaten alone.",
    "Act like an old lady or an old man.",
    "Take two shots of a dark and a light liquor ( 4 shots total).",
    "Go a whole minute without blinking.",
    "Go to Facebook and find the latest wall post you’ve received. Answer it with: “No, you’re wrong!”.",
    "Say “ya heard meh” after everything you say for the next 5 minutes.",
    "Close your eyes and guess 5 objects chosen by the others.",
    "Give a concert with your air guitar.",
    "Email one of your professor’s and tell them you love them.",
    "Pretend to be a waiter or waitress and take snack orders from everyone in the group. Bring them the food they ordered and then check back to see if they like it.",
    "You can’t speak for 2 rounds.",
    "Cross your eyes.",
    "Call one player ‘Your Majesty’ for 5 rounds.",
    "Lick your nose.",
    "Tell a funny knock knock joke.",
    "Act like a pig until it is your turn again.",
    "Whisper for 2 rounds.",
    "You cannot speak for the rest of the game until someone says your name.",
    "Get on all fours and act like a dog until your next turn.",
    "Stick your finger inside the toilet bowl.",
    "Drink something prepared by the others.",
    "Add “Junior” after your last name on your Facebook profile.",
    "See how many ice cubes you can fit in your mouth at one time.",
    "Put an ice cube in your pants and allow it to melt.",
    "Wear a finger mustache for the next 5 minutes.",
    "Eat a spoon of mayo.",
    "Talk with a weird accent for 2 rounds.",
    "Jump around the table on one foot.",
    "I dare you to Stand up for 2 turns.",
    "Lift up the smallest person in the room.",
    "Wear a “Kick me!” sign for the rest of the game.",
    "Ride another player like a horse and do your best & loudest “Yeee Hawww”.",
    "Send a text message saying “I love you” to three people.",
    "Ask for permission the next time you need to use the washroom.",
    "Act like a statue until it is your turn again (no talking or moving).",
    "Combine two foods that should never go together, such as pickles and peanut butter or applesauce and olives, and eat a huge bite.",
    "Recite the multiplication table of 9.",
    "Empty your wallet, pockets and purse and explain the contents.",
    "Choose anyone in the room and smell their feet for 10 seconds.",
    "Show everything that is in your purse.",
    "Meow like cat.",
    "Eat a snack without using your hands.",
    "Give up your smartphone for the rest of the day.",
    "Go to the neighbor’s house and ask for a banana.",
    "Do 10 push-ups or 20 crunches.",
    "Imitate an old grumpy man ranting about the old times.",
    "Send a text message to your last called number asking “What’s your problem?”.",
    "Skip around the room.",
    "Do a handstand on the wall for the next two rounds.",
    "Be a human blanket (warm someone up).",
    "Prank call a local restaurant and order one of everything on the menu.",
    "Choose a foreign language and talk about yourself for at least 1 minute.",
    "Do a gymnastics exercise.",
    "Hold your breath for 10 seconds.",
    "Sit upside down in a chair until your next turn."
]
